### PR TITLE
10.232.*.* support

### PR DESCRIPTION
**Pull request by poying**

### CODE REVIEW

**Comment by dead-horse** [comment]
i prefer to make ip checker as a independent module, and have good test on it.

**Comment by poying** [comment]
How about this
https://github.com/poying/ipchecker

**Comment by dead-horse** [comment]
good.  fix this PR?

**Comment by dead-horse** [comment]
it’s up to you                             原始邮件                             发件人: Po-Ying Chennotifications@github.com收件人: dead-horse/koa-limitkoa-limit@noreply.github.com抄送: dead_horsedead_horse@qq.com发送时间: 2014年3月13日(周四) 21:27主题: Re: [koa-limit] 10.232._._ support (#2)Create a new RP ?

**Comment by dead-horse** [comment]
test failed?

**Comment by poying** [comment]
oops
:p

**Comment by dead-horse** [comment]
thanks!

**Comment by dead-horse** [comment]
`koa-limit`@`1.0.0`

**Pull request merged**
